/**
 * Abbreviated judgment lines (one per hexagram, King Wen order 1–64).
 * Replace or extend with full Wilhelm/Baynes from your open corpus; keep bundle small.
 */
export const WILHELM_JUDGMENTS: readonly string[] = [
  'The creative works sublime success, furthering through perseverance.',
  'The receptive brings sublime success, through the perseverance of a mare.',
  'Difficulty at the beginning: gathering support, appointing helpers.',
  'Youthful folly: learn, do not persist in error.',
  'Waiting: nourishment, confidence, no fault.',
  'Contention: sincerity is blocked; middle way ends well.',
  'The army: discipline and the great man — good fortune, no blame.',
  'Holding together: seek union with the right people.',
  'Small taming: restraint in small things brings success.',
  'Treading: careful conduct on the tail of the tiger — no blame.',
  'Peace: small departs, great approaches; good fortune.',
  'Standstill: evil people prosper; the wise withdraw.',
  'Fellowship: clarity in the open; success for the great.',
  'Great possession: the great man prospers; good fortune.',
  'Modesty: success; the noble carries it through.',
  'Enthusiasm: music and movement; mobilize the people.',
  'Following: adapt; perseverance furthers.',
  'Decay: repair what is rotten; a day for action.',
  'Approach: the eight months — perseverance brings reward.',
  'Watching: sacrifice, washed heart — progress.',
  'Breaking-through: the decisive moment; tell the king.',
  'Biting through: punish obstacles; clarity helps.',
  'Grace: adornment; no lasting dwelling, travel brings gain.',
  'Splitting apart: the mountain rests on earth; above is not kind.',
  'Return: the turning point; seven days — friends come.',
  'Innocence: unexpected truth; the first augury is supreme.',
  'Great taming: restrain the strong; persevere — good fortune.',
  'Corners of the mouth: sources of nourishment — be mindful.',
  'Preponderance of the great: the ridgepole sags — success in small things.',
  'The abysmal repeated: if sincere, action brings honor.',
  'The clinging: clarity — soft rises and succeeds.',
  'Influence: mutual influence — success, marriage good.',
  'Duration: lasting way — success, no blame, perseverance furthers.',
  'Retreat: withdraw in time — small men, not the great.',
  'Great power: truth in thunder — perseverance furthers.',
  'Progress: the sun at noon — the great receives favor.',
  'Darkening: light wounded; be like the earth — hidden lines.',
  'Family: the woman’s domain — perseverance furthers.',
  'Opposition: small matters succeed despite distance.',
  'Obstruction: southwest not, northeast yes; see the great man.',
  'Deliverance: pardon; the south and west — early rain, blessing.',
  'Decrease: sincerity with two bowls — timing, success.',
  'Increase: it furthers to have somewhere to go; sacrifice helps.',
  'Coming to meet: the maiden is strong — do not marry her.',
  'Gathering: the king approaches his temple — success.',
  'Pushing upward: great perseverance — use the south, no blame.',
  'Wearying: sincerity in distress — the great man succeeds.',
  'Gathering the waters: the king maintains the temple — success.',
  'Treading: the sensitive toe — vigilance, blameless.',
  'The well: village, not the rope — the jug is broken.',
  'Revolution: on your own day you are believed — great success.',
  'The cauldron: refining character — great success, auspicious.',
  'Shock: thunder comes — fear then laughter; the shock spreads.',
  'Keeping still: back still; no body — walking in the courtyard.',
  'Development: the maiden given — good fortune, ten years.',
  'The marrying maiden: action brings misfortune; no place furthers.',
  'Abundance: success; the king attains abundance — do not grieve.',
  'The wanderer: success through smallness — perseverance helps.',
  'Gentle: small success; the great goes and comes.',
  'Joyous: openness — progress, steadfastness helps.',
  'Dispersion: the king reaches the temple — success across the great water.',
  'Limitation: number and measure — bitter work, success.',
  'Inner truth: pigs and fish — good fortune, crossing the river.',
  'Small preponderance: the bird flies — success in small matters.',
  'After completion: success in small matters — beginnings good, endings scattered.',
  'Before completion: the fox wets his tail — no completion yet.',
];

export function judgmentForHexagram(hexagramIndex: number): string {
  const i = ((hexagramIndex % 64) + 64) % 64;
  return WILHELM_JUDGMENTS[i] ?? '';
}
